package com.resumestudio.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The cover-letter catalogue, mirroring `CoverLetterTemplate`.
 *
 * GENERATED by `tools/generate-cover-letter-templates.py` — regenerate rather
 * than hand-edit, the same rule the résumé catalogue follows.
 *
 * [pairsWith] is the résumé template this one was drawn to sit beside. A letter
 * and a résumé sharing a letterhead is the point of the pairing; the ones with
 * no pair stand on their own.
 */
@Serializable
enum class CoverLetterTemplate(
    val wireName: String,
    val title: String,
    val pairsWith: ResumeTemplate?,
) {
    @SerialName("modern") MODERN("modern", "Modern Professional", null),
    @SerialName("gradient") GRADIENT("gradient", "Gradient Banner", null),
    @SerialName("executive") EXECUTIVE("executive", "Executive Header", null),
    @SerialName("monogram") MONOGRAM("monogram", "Monogram Mark", null),
    @SerialName("sidebar") SIDEBAR("sidebar", "Sidebar Letterhead", ResumeTemplate.ATLAS),
    @SerialName("minimal") MINIMAL("minimal", "Clean Minimal", null),
    @SerialName("memo") MEMO("memo", "Memo Brief", null),
    @SerialName("iconic") ICONIC("iconic", "Icon Contact", ResumeTemplate.SIGNAL),
    @SerialName("creative") CREATIVE("creative", "Creative Accent", null),
    @SerialName("rail") RAIL("rail", "Rail Note", ResumeTemplate.CHRONICLE),
    @SerialName("portfolio") PORTFOLIO("portfolio", "Portfolio Card", null),
    @SerialName("cardstock") CARDSTOCK("cardstock", "Cardstock", ResumeTemplate.STRATA),
    @SerialName("classic") CLASSIC("classic", "Classic Formal", null),
    @SerialName("letterpress") LETTERPRESS("letterpress", "Letterpress Serif", null),
    @SerialName("broadsheet") BROADSHEET("broadsheet", "Broadsheet", ResumeTemplate.GAZETTE),
    @SerialName("signature") SIGNATURE("signature", "Signature Note", null),
    @SerialName("noir") NOIR("noir", "Noir Ink", ResumeTemplate.NOIR),
    @SerialName("marquee") MARQUEE("marquee", "Marquee Type", ResumeTemplate.MARQUEE),
    @SerialName("crest") CREST("crest", "Crest Banner", ResumeTemplate.CREST),
    @SerialName("ivy") IVY("ivy", "Ivy Formal", ResumeTemplate.IVY),
    @SerialName("plinth") PLINTH("plinth", "Plinth Footer", ResumeTemplate.PLINTH),
    @SerialName("stockholm") STOCKHOLM("stockholm", "Stockholm Note", ResumeTemplate.STOCKHOLM),
    @SerialName("laureate") LAUREATE("laureate", "Laureate Standard", ResumeTemplate.LAUREATE),
    @SerialName("nova") NOVA("nova", "Nova Banner", ResumeTemplate.NOVA),
    @SerialName("aurelia") AURELIA("aurelia", "Aurelia Ornament", ResumeTemplate.AURELIA),
    @SerialName("nocturne") NOCTURNE("nocturne", "Nocturne Serif", ResumeTemplate.NOCTURNE),
    @SerialName("eclipse") ECLIPSE("eclipse", "Eclipse Letter", ResumeTemplate.ECLIPSE),
    @SerialName("vantage") VANTAGE("vantage", "Vantage Statement", ResumeTemplate.VANTAGE),
    @SerialName("zenith") ZENITH("zenith", "Zenith Dispatch", ResumeTemplate.ZENITH),
    @SerialName("aperture") APERTURE("aperture", "Aperture Letter", ResumeTemplate.APERTURE),
    @SerialName("sovereign") SOVEREIGN("sovereign", "Sovereign Letterhead", ResumeTemplate.SOVEREIGN),
    @SerialName("blueprint") BLUEPRINT("blueprint", "Blueprint Brief", ResumeTemplate.BLUEPRINT),
    @SerialName("spectrum") SPECTRUM("spectrum", "Spectrum Statement", ResumeTemplate.SPECTRUM),
    @SerialName("halo") HALO("halo", "Halo Correspondence", ResumeTemplate.HALO),
    @SerialName("volta") VOLTA("volta", "Volta Manifesto", ResumeTemplate.VOLTA),
    @SerialName("obsidian") OBSIDIAN("obsidian", "Obsidian Letter", ResumeTemplate.OBSIDIAN),
    @SerialName("radiant") RADIANT("radiant", "Radiant Halo Letter", ResumeTemplate.RADIANT),
    @SerialName("verge") VERGE("verge", "Verge Duotone Letter", ResumeTemplate.VERGE),
    @SerialName("datum") DATUM("datum", "Datum Brief", ResumeTemplate.DATUM),
    @SerialName("pinnacle") PINNACLE("pinnacle", "Pinnacle Letterhead", ResumeTemplate.PINNACLE),
    @SerialName("emblem") EMBLEM("emblem", "Emblem Monogram Letter", ResumeTemplate.EMBLEM),
    @SerialName("cadence") CADENCE("cadence", "Cadence Note", ResumeTemplate.CADENCE),
    @SerialName("citadel") CITADEL("citadel", "Citadel Dispatch", ResumeTemplate.CITADEL),
    @SerialName("stratus") STRATUS("stratus", "Stratus Statement", ResumeTemplate.STRATUS),
    @SerialName("mirage") MIRAGE("mirage", "Mirage Letter", ResumeTemplate.MIRAGE),
    @SerialName("salute") SALUTE("salute", "Salute Greeting Letter", ResumeTemplate.SALUTE),
    @SerialName("couture") COUTURE("couture", "Couture Vertical Letter", ResumeTemplate.COUTURE),
    @SerialName("medallion") MEDALLION("medallion", "Medallion Seal Letter", ResumeTemplate.MEDALLION),
    @SerialName("sable") SABLE("sable", "Sable Sidebar Letter", ResumeTemplate.SABLE),
    @SerialName("terracotta") TERRACOTTA("terracotta", "Terracotta Circle Letter", ResumeTemplate.TERRACOTTA),
    @SerialName("lozenge") LOZENGE("lozenge", "Lozenge Pill Letter", ResumeTemplate.LOZENGE),
    @SerialName("circlet") CIRCLET("circlet", "Circlet Orbit Letter", ResumeTemplate.CIRCLET),
    @SerialName("vogue") VOGUE("vogue", "Vogue Editorial Letter", ResumeTemplate.VOGUE),
    @SerialName("signet") SIGNET("signet", "Signet Seal Letter", ResumeTemplate.SIGNET),
    @SerialName("almanac") ALMANAC("almanac", "Almanac Brief Letter", ResumeTemplate.ALMANAC),
    @SerialName("kintsugi") KINTSUGI("kintsugi", "Kintsugi Gold Letter", ResumeTemplate.KINTSUGI),
    @SerialName("bauhaus") BAUHAUS("bauhaus", "Bauhaus Signal Letter", ResumeTemplate.BAUHAUS),
    @SerialName("terminal") TERMINAL("terminal", "Terminal Command Letter", ResumeTemplate.TERMINAL),
    @SerialName("topograph") TOPOGRAPH("topograph", "Topograph Field Letter", ResumeTemplate.TOPOGRAPH),
    @SerialName("passport") PASSPORT("passport", "Passport Profile Letter", ResumeTemplate.PASSPORT),
    @SerialName("transit") TRANSIT("transit", "Transit Map Letter", ResumeTemplate.TRANSIT),
    @SerialName("cutline") CUTLINE("cutline", "Cutline Editorial Letter", ResumeTemplate.CUTLINE),
    @SerialName("receipt") RECEIPT("receipt", "Receipt One-Page Letter", ResumeTemplate.RECEIPT),
    @SerialName("constellation") CONSTELLATION("constellation", "Constellation Story Letter", ResumeTemplate.CONSTELLATION),
    @SerialName("studioFolio") STUDIO_FOLIO("studioFolio", "Studio Folio Letter", null),
    ;

    companion object {
        private val byWireName = entries.associateBy(CoverLetterTemplate::wireName)

        fun from(wireName: String): CoverLetterTemplate? = byWireName[wireName]

        /** The letter drawn to match [template], if one was. */
        fun pairedWith(template: ResumeTemplate): CoverLetterTemplate? =
            entries.firstOrNull { it.pairsWith == template }
    }
}
