package com.resumestudio.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The accent palettes, mirroring `ResumeAccent` in `ResumeDocument.swift`.
 *
 * GENERATED by `tools/generate-accents.py` — regenerate rather than hand-edit.
 *
 * The components are kept as the same floats iOS writes rather than being packed
 * into 8-bit hex here. Rounding to hex is a step the renderer takes at the very
 * end on both platforms; doing it early would put an off-by-one into an exported
 * PDF that nobody could trace back.
 *
 * [tier] records why a colour is where it is. The renderer never consults it —
 * entitlement is settled before a document reaches it — but the gallery does.
 */
@Serializable
enum class ResumeAccent(
    val wireName: String,
    val title: String,
    val red: Float,
    val green: Float,
    val blue: Float,
    val tier: Tier,
) {
    // The four original accents ship free; every richer tone is part of the
    // subscription, checked through PurchaseManager on iOS.
    @SerialName("orange") ORANGE("orange", "Burnt Orange", 0.82f, 0.28f, 0.04f, Tier.INCLUDED),
    @SerialName("blue") BLUE("blue", "Deep Blue", 0.11f, 0.38f, 0.70f, Tier.INCLUDED),
    @SerialName("teal") TEAL("teal", "Pine Teal", 0.05f, 0.47f, 0.47f, Tier.INCLUDED),
    @SerialName("burgundy") BURGUNDY("burgundy", "Burgundy", 0.55f, 0.10f, 0.21f, Tier.INCLUDED),

    // The Signature palette: five jewel accents gated behind a subscription,
    // the same way the premium templates are.
    @SerialName("emerald") EMERALD("emerald", "Emerald", 0.06f, 0.45f, 0.31f, Tier.SIGNATURE),
    @SerialName("amethyst") AMETHYST("amethyst", "Amethyst", 0.45f, 0.26f, 0.60f, Tier.SIGNATURE),
    @SerialName("sapphire") SAPPHIRE("sapphire", "Sapphire", 0.13f, 0.24f, 0.58f, Tier.SIGNATURE),
    @SerialName("rose") ROSE("rose", "Rose Gold", 0.79f, 0.32f, 0.44f, Tier.SIGNATURE),
    @SerialName("midnight") MIDNIGHT("midnight", "Midnight", 0.14f, 0.18f, 0.28f, Tier.SIGNATURE),

    // The Atelier palette: five more refined tones, also part of the subscription.
    @SerialName("bronze") BRONZE("bronze", "Bronze", 0.63f, 0.44f, 0.18f, Tier.ATELIER),
    @SerialName("graphite") GRAPHITE("graphite", "Graphite", 0.26f, 0.29f, 0.33f, Tier.ATELIER),
    @SerialName("plum") PLUM("plum", "Plum", 0.42f, 0.18f, 0.38f, Tier.ATELIER),
    @SerialName("steel") STEEL("steel", "Steel Blue", 0.28f, 0.42f, 0.53f, Tier.ATELIER),
    @SerialName("terracotta") TERRACOTTA("terracotta", "Terracotta", 0.75f, 0.39f, 0.28f, Tier.ATELIER),

    // The Luxe palette: six nuanced, high-contrast tones designed to feel rich
    // on screen while remaining clear and professional in exported documents.
    @SerialName("champagne") CHAMPAGNE("champagne", "Champagne Gold", 0.608f, 0.431f, 0.141f, Tier.LUXE),
    @SerialName("peacock") PEACOCK("peacock", "Peacock", 0.04f, 0.40f, 0.44f, Tier.LUXE),
    @SerialName("mulberry") MULBERRY("mulberry", "Mulberry", 0.54f, 0.20f, 0.37f, Tier.LUXE),
    @SerialName("moss") MOSS("moss", "Moss", 0.36f, 0.42f, 0.23f, Tier.LUXE),
    @SerialName("cobalt") COBALT("cobalt", "Cobalt", 0.20f, 0.31f, 0.64f, Tier.LUXE),
    @SerialName("cocoa") COCOA("cocoa", "Cocoa", 0.42f, 0.28f, 0.24f, Tier.LUXE),
    ;

    enum class Tier { INCLUDED, SIGNATURE, ATELIER, LUXE }

    /** Mirrors `isPremium`: everything outside the original four is subscriber-only. */
    val isPremium: Boolean get() = tier != Tier.INCLUDED

    /** Opaque 0xAARRGGBB, rounded only here, at the point of use. */
    val argb: Int
        get() = (0xFF shl 24) or
            (channel(red) shl 16) or
            (channel(green) shl 8) or
            channel(blue)

    private fun channel(value: Float): Int = (value * 255f + 0.5f).toInt().coerceIn(0, 255)

    companion object {
        private val byWireName = entries.associateBy(ResumeAccent::wireName)

        fun from(wireName: String): ResumeAccent? = byWireName[wireName]
    }
}
